
# CSAP agent sets based on lifecycle
spring.profiles.active: desktop

---
#
#    Common Config
#

# Service Settings
my-service-configuration: 
  locator: 
    hello-provider: "BootReference"
    hello-api: "/helloNoSecurity"
    
# Disable fallback to basic auth, use LDAP or not based on the above
security.basic.enabled: false

server:
  port: 8090
  context-path: /BootReference
  session:
    persistent: false
  error:
    include-stacktrace: always


# @CsapBootApplication
csap:

  baseContext: /csap
  
  info:
    name: "${csapName:MyDesktop}"
    load-balancer-url: "${csapLbUrl:http://csap-secure.yourcompany.com}"
    lifecycle: "${csapLife:dev}"
    version: "${csapVersion:1.0-Desktop}"
    http-port: "${csapHttpPort:8090}" 
    working-dir: "${csapWorkingDir:/the/path/to/app}" 
    cluster: "${csapName:dev-desktop-1}"
    
  debug:
    show-web-params:
        enabled: true
        include-headers: true
        urls:
        - "/hello"
      
  documentation:
    enabled: true
      
  encryptable-properties:
    enabled: true
    property-files: 
      - csapSecurity.properties
      
  web-server:
    enabled: true
    ajp-secret: ${csapAjp:ThisWillBeReplaced}
  
  security:
    enabled: true
    ldap-enabled: true
    rest-api-filter:
      enabled: true
      urls:
        - "/demoUrl1/*"
        - "/demoUrl2/*"
        - "/helloWithRestAcl"
      group: "$CSAP_ADMIN_GROUP"
      cache-seconds: 300
  
  performance:
    enabled: true
    
    monitor-urls: 
        - /
        - /admin/*
        - /security/*
        
    
    alert:
    
      debug: false
      
      report:
        frequency: 30
        time-unit: SECONDS 
      
      remember-count: ${csapMaxBacklog:1000}
      
      throttle: 
        count: 5
        frequency: 1
        time-unit: HOURS 
      
      notify: 
        # addresses: "${csapAddresses:yourid@yourcompany.com}"
        frequency: "${csapFrequency:4}"
        time-unit: "${csapTimeUnit:HOURS}"
        
      limits: 
        - 
          id: health.exceptions
          ignore-null: true
          occurences-max: 0
          collect-time: 30
          collect-units: SECONDS
        - 
          id: health.nullPointer
          ignore-null: true
          occurences-max: 0
        - 
          id: controller.LandingPage.get()
          ignore-null: true
          occurences-max: 10
          mean-time:  100
          mean-units: SECONDS
          max-time: 1
          max-units: SECONDS
        - 
          id: http..GET
          ignore-null: true
          occurences-min: 0
          occurences-max: 10
          mean-time:  100
          max-time: 1
          max-units: SECONDS
        
  locator:
    enabled: true
    active-urls-locator: "${csapLbUrl:https://csap-secure.yourcompany.com}/admin/api/service/urls/active/"
    low-resources-url-locator: "${csapLbUrl:https://csap-secure.yourcompany.com}/admin/api/service/url/low/"
    low-resource: "lowCpu"  #lowLoad, lowCpu, ...
    



# Spring Boot actuator exposes several endpoints, and csap security is used to authenticate
management:
  context-path: /devOps
  security:
    enabled: true

# Spring actuator: info settings
info:
  build.profile: ${spring.profiles.active}
  build.artifact: "Maven: @project.artifactId@"
  build.name: "@project.name@"
  build.description: "@project.description@"
  build.version: "@project.version@"
 
spring:
  resources:
    cache-period: 32000000  # 1 year
  aop:
    proxy-target-class: true
  thymeleaf:
    mode: HTML




---

#
#  ================ desktop configuration
#
 

spring:
    profiles: desktop
      
server:
  tomcat:
    max-threads: 20
    
  context-path: /
    
    
csap:
  web-server:
    enabled: true
    max-connections-ajp: 10
    max-connections-http: 10
    backlog: 1
    ajp-secret: ${csapAjp:ThisWillBeReplaced}
    ajp-secure: false
    ajp-scheme: http
    ajp-proxy-port: 443
    ajp-redirect-port: 443
  
  security: 
    enabled: false
    ldap-enabled: false   # requires csapSecurity.properties in your home dir
    csrf-enabled: false
    max-concurrent-user-sessions: 0 #unlimited
    
  encryptable-properties:
    enabled: true
    algorithm: PBEWITHMD5ANDDES
    property-files:
      - "csapSecurity.properties"
      - "${csapTest}/csapSecurity.properties"   #overwrite the above if it exists


---
#
#  Junit tests: different profiles will force application context caching
#
spring:
    profiles: junit
    cache:
      type: none  # cachemanager lifecycles will impact, so disable
    
server:
  context-path: /
  
      
csap:
  web-server.enabled: false
  security.enabled: false
  performance.enabled: true
  encryptable-properties:
    enabled: true
    token: "Will be overwritten by env var"
    algorithm: PBEWITHMD5ANDDES 

---
#
#  Junit tests: different profiles will force application context caching
#
spring:
    profiles: mockJunit
    cache:
      type: none  # cachemanager lifecycles will impact, so disable
    
server:
  context-path: /
  
      
csap:
  web-server.enabled: false
  security.enabled: false
  performance.enabled: true
  encryptable-properties:
    enabled: true
    token: "Will be overwritten by env var"
    algorithm: PBEWITHMD5ANDDES 

---
#
#  Junit tests: different profiles will force application context caching
#
spring:
    profiles: htmlUnit
    cache:
      type: none  # cachemanager lifecycles will impact, so disable
    
server:
  context-path: /
  
      
csap:
  web-server.enabled: false
  security.enabled: false
  performance.enabled: false
  encryptable-properties:
    enabled: true
    token: "Will be overwritten by env var"
    algorithm: PBEWITHMD5ANDDES 
    
    